services:
  shadowsocks:
    image: vndroid/shadowsocks-libev:alpine
    expose:
      - 8388/tcp
      - 8388/udp
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9MLSpPmNt
    restart: always
    networks:
      - backend
  openresty:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
      - "443:443"
      - "18388:18388/tcp"
      - "18388:18388/udp"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./allow.list:/etc/openresty/allow.list
      - ./htpasswd:/etc/openresty/.htpasswd
    restart: always
    networks:
      - backend
    depends_on:
      - shadowsocks
networks:
  backend: